-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.account_subreddit_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid,
  subreddit text NOT NULL,
  priority integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT account_subreddit_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT account_subreddit_assignments_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.reddit_accounts(id),
  CONSTRAINT account_subreddit_assignments_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.automation_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  session_id text NOT NULL,
  subreddit text,
  total_posts integer DEFAULT 0,
  processed_count integer DEFAULT 0,
  success_count integer DEFAULT 0,
  failed_count integer DEFAULT 0,
  status text DEFAULT 'running'::text,
  completed_at timestamp with time zone,
  team_id uuid,
  CONSTRAINT automation_logs_pkey PRIMARY KEY (id),
  CONSTRAINT automation_logs_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.automation_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  default_queue_mode text DEFAULT 'review'::text CHECK (default_queue_mode = ANY (ARRAY['auto'::text, 'review'::text, 'manual'::text])),
  min_relevance_score integer DEFAULT 40,
  allow_weak_matches boolean DEFAULT true,
  min_account_age_days integer DEFAULT 30,
  min_karma integer DEFAULT 100,
  block_suspected_bots boolean DEFAULT true,
  global_daily_limit integer DEFAULT 100,
  delay_between_dms_min integer DEFAULT 30,
  delay_between_dms_max integer DEFAULT 180,
  enable_session_breaks boolean DEFAULT true,
  session_break_after_min integer DEFAULT 5,
  session_break_after_max integer DEFAULT 15,
  session_break_duration_min integer DEFAULT 300,
  session_break_duration_max integer DEFAULT 1800,
  typing_speed_min integer DEFAULT 50,
  typing_speed_max integer DEFAULT 150,
  enable_typo_simulation boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT automation_settings_pkey PRIMARY KEY (id),
  CONSTRAINT automation_settings_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  subreddits jsonb DEFAULT '[]'::jsonb,
  message_tone text,
  target_persona text,
  business_context text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'completed'::text, 'archived'::text])),
  total_scanned integer DEFAULT 0,
  total_qualified integer DEFAULT 0,
  total_dms integer DEFAULT 0,
  replies_received integer DEFAULT 0,
  conversions integer DEFAULT 0,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reddit_conversation_id text UNIQUE,
  participant_username text NOT NULL,
  account_id uuid,
  initial_dm_id uuid,
  initial_queue_id uuid,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'interested'::text, 'cold'::text, 'closed'::text, 'converted'::text])),
  last_message_at timestamp with time zone,
  last_message_direction text CHECK (last_message_direction = ANY (ARRAY['inbound'::text, 'outbound'::text])),
  total_messages integer DEFAULT 0,
  has_reply boolean DEFAULT false,
  notes text,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.reddit_accounts(id),
  CONSTRAINT conversations_initial_dm_id_fkey FOREIGN KEY (initial_dm_id) REFERENCES public.dm_history(id),
  CONSTRAINT conversations_initial_queue_id_fkey FOREIGN KEY (initial_queue_id) REFERENCES public.dm_queue(id),
  CONSTRAINT conversations_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.dm_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  recipient_username text NOT NULL,
  post_url text,
  post_title text,
  subreddit text,
  message_content text NOT NULL,
  status text DEFAULT 'sent'::text,
  automation_type text,
  session_id text,
  account_id uuid,
  classification_id uuid,
  campaign_id uuid,
  team_id uuid,
  CONSTRAINT dm_history_pkey PRIMARY KEY (id),
  CONSTRAINT dm_history_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.reddit_accounts(id),
  CONSTRAINT dm_history_classification_id_fkey FOREIGN KEY (classification_id) REFERENCES public.post_classifications(id),
  CONSTRAINT dm_history_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT dm_history_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.dm_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid,
  recipient_username text NOT NULL,
  subreddit text,
  post_url text,
  post_title text,
  post_body text,
  classification_id uuid,
  classification_score double precision,
  classification_category text,
  generated_message text NOT NULL,
  edited_message text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'sent'::text, 'failed'::text, 'expired'::text])),
  queue_mode text NOT NULL CHECK (queue_mode = ANY (ARRAY['auto'::text, 'review'::text, 'manual'::text])),
  scheduled_at timestamp with time zone,
  approved_at timestamp with time zone,
  approved_by text,
  sent_at timestamp with time zone,
  failed_reason text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  message_type text NOT NULL DEFAULT 'outreach'::text,
  conversation_id uuid,
  CONSTRAINT dm_queue_pkey PRIMARY KEY (id),
  CONSTRAINT dm_queue_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.reddit_accounts(id),
  CONSTRAINT dm_queue_classification_id_fkey FOREIGN KEY (classification_id) REFERENCES public.post_classifications(id),
  CONSTRAINT dm_queue_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT dm_queue_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.filter_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  rule_type text NOT NULL CHECK (rule_type = ANY (ARRAY['keyword_skip'::text, 'keyword_require'::text, 'karma_min'::text, 'account_age_min'::text, 'subreddit_blacklist'::text, 'subreddit_whitelist'::text, 'relevance_score_min'::text])),
  value jsonb NOT NULL,
  is_active boolean DEFAULT true,
  priority integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT filter_rules_pkey PRIMARY KEY (id),
  CONSTRAINT filter_rules_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.lead_funnel (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL,
  subreddit text,
  campaign_id uuid,
  account_id uuid,
  scanned integer DEFAULT 0,
  qualified integer DEFAULT 0,
  messaged integer DEFAULT 0,
  replied integer DEFAULT 0,
  converted integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT lead_funnel_pkey PRIMARY KEY (id),
  CONSTRAINT lead_funnel_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT lead_funnel_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.reddit_accounts(id),
  CONSTRAINT lead_funnel_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.member_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid,
  user_id uuid,
  date date NOT NULL,
  dms_sent integer DEFAULT 0,
  dms_approved integer DEFAULT 0,
  responses integer DEFAULT 0,
  accounts_managed integer DEFAULT 0,
  CONSTRAINT member_stats_pkey PRIMARY KEY (id),
  CONSTRAINT member_stats_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT member_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['inbound'::text, 'outbound'::text])),
  content text NOT NULL,
  sent_at timestamp with time zone NOT NULL,
  is_ai_generated boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  fingerprint text,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.post_classifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_url text NOT NULL UNIQUE,
  post_title text,
  post_body text,
  subreddit text,
  author text,
  relevance_score integer CHECK (relevance_score >= 0 AND relevance_score <= 100),
  buyer_intent_score integer CHECK (buyer_intent_score >= 0 AND buyer_intent_score <= 100),
  problem_awareness_score integer CHECK (problem_awareness_score >= 0 AND problem_awareness_score <= 100),
  product_fit_score integer CHECK (product_fit_score >= 0 AND product_fit_score <= 100),
  confidence_score integer CHECK (confidence_score >= 0 AND confidence_score <= 100),
  category text NOT NULL CHECK (category = ANY (ARRAY['strong_match'::text, 'weak_match'::text, 'not_relevant'::text])),
  reasoning text,
  classified_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  created_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT post_classifications_pkey PRIMARY KEY (id),
  CONSTRAINT post_classifications_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.reddit_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL UNIQUE,
  display_name text,
  encrypted_cookie text,
  warmup_mode boolean DEFAULT true,
  warmup_start_date timestamp with time zone DEFAULT now(),
  daily_limit integer DEFAULT 20,
  current_daily_count integer DEFAULT 0,
  last_daily_reset timestamp with time zone DEFAULT now(),
  last_dm_at timestamp with time zone,
  last_activity_at timestamp with time zone,
  is_shadowbanned boolean DEFAULT false,
  shadowban_checked_at timestamp with time zone,
  shadowban_check_result jsonb,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'warming_up'::text, 'shadowbanned'::text, 'suspended'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT reddit_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT reddit_accounts_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.safety_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid,
  event_type text NOT NULL,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT safety_events_pkey PRIMARY KEY (id),
  CONSTRAINT safety_events_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.reddit_accounts(id),
  CONSTRAINT safety_events_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.skipped_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_url text NOT NULL,
  post_title text,
  subreddit text,
  author text,
  session_id text,
  campaign_id uuid,
  skip_reason text NOT NULL,
  skip_details jsonb,
  classification_id uuid,
  qualification_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT skipped_posts_pkey PRIMARY KEY (id),
  CONSTRAINT skipped_posts_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT skipped_posts_classification_id_fkey FOREIGN KEY (classification_id) REFERENCES public.post_classifications(id),
  CONSTRAINT skipped_posts_qualification_id_fkey FOREIGN KEY (qualification_id) REFERENCES public.user_qualifications(id),
  CONSTRAINT skipped_posts_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid,
  user_id uuid,
  action text NOT NULL,
  resource_type text,
  resource_id uuid,
  details jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT team_audit_log_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.team_daily_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid,
  date date NOT NULL,
  dms_sent integer DEFAULT 0,
  dms_delivered integer DEFAULT 0,
  dms_failed integer DEFAULT 0,
  response_count integer DEFAULT 0,
  avg_response_time_mins double precision,
  leads_generated integer DEFAULT 0,
  positive_responses integer DEFAULT 0,
  negative_responses integer DEFAULT 0,
  active_accounts integer DEFAULT 0,
  unique_recipients integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_daily_stats_pkey PRIMARY KEY (id),
  CONSTRAINT team_daily_stats_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_hourly_activity (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid,
  date date NOT NULL,
  hour integer NOT NULL CHECK (hour >= 0 AND hour < 24),
  dms_sent integer DEFAULT 0,
  responses integer DEFAULT 0,
  CONSTRAINT team_hourly_activity_pkey PRIMARY KEY (id),
  CONSTRAINT team_hourly_activity_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  email text NOT NULL,
  role text DEFAULT 'member'::text CHECK (role = ANY (ARRAY['admin'::text, 'member'::text])),
  token text NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'::text) UNIQUE,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT team_invitations_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_invitations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text DEFAULT 'member'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text])),
  invited_by uuid,
  joined_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT team_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.team_quotas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid UNIQUE,
  max_accounts integer DEFAULT 5,
  max_dms_per_day integer DEFAULT 100,
  max_members integer DEFAULT 10,
  max_campaigns integer DEFAULT 10,
  max_rules integer DEFAULT 50,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_quotas_pkey PRIMARY KEY (id),
  CONSTRAINT team_quotas_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid,
  date date DEFAULT CURRENT_DATE,
  dms_sent integer DEFAULT 0,
  dms_received integer DEFAULT 0,
  accounts_active integer DEFAULT 0,
  api_calls integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_usage_pkey PRIMARY KEY (id),
  CONSTRAINT team_usage_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  owner_id uuid NOT NULL,
  settings jsonb DEFAULT '{}'::jsonb,
  is_personal boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL UNIQUE,
  interests jsonb DEFAULT '[]'::jsonb,
  pain_points jsonb DEFAULT '[]'::jsonb,
  communication_style jsonb DEFAULT '{}'::jsonb,
  professional_signals jsonb DEFAULT '{}'::jsonb,
  purchase_signals jsonb DEFAULT '[]'::jsonb,
  peak_activity jsonb DEFAULT '{}'::jsonb,
  optimal_send_time jsonb DEFAULT '{}'::jsonb,
  personalization_context jsonb DEFAULT '{}'::jsonb,
  analyzed_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.user_qualifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL UNIQUE,
  account_age_days integer,
  total_karma integer,
  post_karma integer,
  comment_karma integer,
  account_created_at timestamp with time zone,
  posting_frequency text CHECK (posting_frequency = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text, 'inactive'::text])),
  primary_subreddits ARRAY,
  professional_signals ARRAY,
  account_quality_score integer CHECK (account_quality_score >= 0 AND account_quality_score <= 100),
  engagement_score integer CHECK (engagement_score >= 0 AND engagement_score <= 100),
  is_bot_likely boolean DEFAULT false,
  is_spam_likely boolean DEFAULT false,
  is_qualified boolean DEFAULT true,
  disqualification_reason text,
  qualified_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  created_at timestamp with time zone DEFAULT now(),
  team_id uuid,
  CONSTRAINT user_qualifications_pkey PRIMARY KEY (id),
  CONSTRAINT user_qualifications_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.user_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_desc text,
  persona text,
  insight_types ARRAY,
  tone text DEFAULT 'Curious'::text,
  team_id uuid,
  CONSTRAINT user_settings_pkey PRIMARY KEY (id),
  CONSTRAINT user_settings_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);